services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    restart: unless-stopped

  planeta:
    build: .
    env_file:
      - docker.env
