# fly.toml app configuration file generated for planetapeia-desfiles on 2024-02-20T22:46:17-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'planetapeia-desfiles'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'
  FLY_APP_NAME = 'planetapeia-desfiles.fly.dev'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
