# Generated by Django 5.0.2 on 2024-02-08 16:54

import desfiles.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Desfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=64, verbose_name="Nome")),
                (
                    "local",
                    models.CharField(default="", max_length=64, verbose_name="Local"),
                ),
                ("data", models.DateField(verbose_name="Data")),
            ],
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=48, verbose_name="Nome")),
                (
                    "imagem",
                    models.ImageField(
                        upload_to=desfiles.models.upload_to, verbose_name="Imagem"
                    ),
                ),
                (
                    "tipo_cobranca_traje",
                    models.BooleanField(default=True, verbose_name="Cobrar traje"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=40, verbose_name="Nome")),
                (
                    "imagem",
                    models.ImageField(
                        upload_to=desfiles.models.upload_to, verbose_name="Imagem"
                    ),
                ),
                (
                    "capacidade",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Capacidade mínima"
                            ),
                            django.core.validators.MaxValueValidator(
                                99, "Capacidade máxima"
                            ),
                        ],
                        verbose_name="Capacidade",
                    ),
                ),
                (
                    "qtd_staffs",
                    models.IntegerField(
                        help_text="Inclui condutor e staffs", verbose_name="Qtd Staffs"
                    ),
                ),
                (
                    "qtd_max_criancas",
                    models.IntegerField(default=0, verbose_name="Qtd Max Crianças"),
                ),
                (
                    "qtd_max_mulheres",
                    models.IntegerField(default=99, verbose_name="Qtd Max Mulheres"),
                ),
                (
                    "qtd_max_homens",
                    models.IntegerField(default=99, verbose_name="Qtd Max Homens"),
                ),
                (
                    "peso_total_max",
                    models.IntegerField(default=0, verbose_name="Peso total máximo"),
                ),
                (
                    "peso_individual_max",
                    models.IntegerField(
                        default=0, verbose_name="Peso individual máximo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "cpf",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        verbose_name="CPF",
                    ),
                ),
                ("nome", models.CharField(max_length=60, verbose_name="Nome")),
                ("telefone", models.CharField(max_length=13, verbose_name="Telefone")),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        max_length=1,
                        verbose_name="Gênero",
                    ),
                ),
                (
                    "peso",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1, "Peso mínimo"),
                            django.core.validators.MaxValueValidator(
                                160, "Peso máximo"
                            ),
                        ],
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "altura",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                30, "Altura mínima"
                            ),
                            django.core.validators.MaxValueValidator(
                                220, "Altura máxima"
                            ),
                        ],
                        verbose_name="Altura (cm)",
                    ),
                ),
                (
                    "tamanho_traje",
                    models.CharField(
                        choices=[
                            ("P", "Pequeno"),
                            ("M", "Médio"),
                            ("G", "Grande"),
                            ("E", "Extra-grande"),
                        ],
                        max_length=1,
                        verbose_name="Tamanho do traje",
                    ),
                ),
                (
                    "pcd",
                    models.BooleanField(
                        default=False, verbose_name="Pessoa com deficiência"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("C", "Convidado"), ("S", "Staff"), ("D", "Condutor")],
                        default="C",
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "tipo_cobranca_traje",
                    models.CharField(
                        choices=[("G", "Seguir grupo"), ("S", "Sim"), ("N", "Não")],
                        default="G",
                        max_length=1,
                        verbose_name="Tipo cobrança traje",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.grupo",
                        verbose_name="Grupo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VeiculoDesfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.desfile",
                        verbose_name="Desfile",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.veiculo",
                        verbose_name="Veículo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InscricaoDesfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aprovacao",
                    models.CharField(
                        choices=[
                            ("P", "Pendente"),
                            ("A", "Aprovado"),
                            ("R", "Rejeitado"),
                        ],
                        default="P",
                        max_length=1,
                        verbose_name="Aprovação",
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data aprovação"
                    ),
                ),
                (
                    "aprovador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovador",
                    ),
                ),
                (
                    "desfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.desfile",
                        verbose_name="Desfile",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.veiculodesfile",
                        verbose_name="Veículo",
                    ),
                ),
            ],
        ),
    ]
