# Generated by Django 5.0.2 on 2024-02-09 18:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desfiles", "0004_desfile_aprovador_desfile_data_aprovacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="padrinho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="desfiles.pessoa",
                verbose_name="Padrinho",
            ),
        ),
        migrations.CreateModel(
            name="Traje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=48, verbose_name="Nome")),
                (
                    "veiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.veiculo",
                        verbose_name="Veículo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrajeInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_inventario",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                        verbose_name="# Inventário",
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        choices=[
                            ("P", "Pequeno"),
                            ("M", "Médio"),
                            ("G", "Grande"),
                            ("E", "Extra-grande"),
                        ],
                        max_length=1,
                        verbose_name="Tamanho",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("D", "Disponível"),
                            ("E", "Emprestado"),
                            ("M", "Em Manutenção"),
                            ("X", "Descartado"),
                        ],
                        max_length=1,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "traje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.traje",
                        verbose_name="Traje",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrajeHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Data")),
                (
                    "obs",
                    models.CharField(
                        default="", max_length=120, verbose_name="Observações"
                    ),
                ),
                (
                    "movimento",
                    models.CharField(
                        choices=[
                            ("E", "Entrada"),
                            ("B", "Empréstimo"),
                            ("D", "Devolução"),
                            ("M", "Manutenção"),
                            ("X", "Descarte"),
                        ],
                        max_length=1,
                        verbose_name="Movimento",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "traje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.trajeinventario",
                        verbose_name="Traje",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrajeTaxa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_taxa",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="R$ taxa",
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="R$ pago",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Pagamento"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[("P", "Pendente"), ("$", "Pago"), ("A", "Abonado")],
                        default="P",
                        max_length=1,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "desfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.desfile",
                        verbose_name="Desfile",
                    ),
                ),
                (
                    "traje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.trajeinventario",
                        verbose_name="Traje",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
        ),
    ]
