# Generated by Django 5.0.2 on 2024-02-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "desfiles",
            "0005_pessoa_padrinho_traje_trajeinventario_trajehistorico_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="traje",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino")],
                default="M",
                max_length=1,
                verbose_name="Gênero",
            ),
            preserve_default=False,
        ),
    ]
