# Generated by Django 5.0.2 on 2024-02-09 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desfiles", "0006_traje_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trajeinventario",
            name="num_inventario",
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="# Inventário",
            ),
        ),
    ]
