# Generated by Django 5.0.2 on 2024-02-09 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desfiles", "0007_alter_trajeinventario_num_inventario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trajetaxa",
            name="traje",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="desfiles.trajehistorico",
                verbose_name="Histórico",
            ),
        ),
    ]
