# Generated by Django 5.0.2 on 2024-02-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desfiles", "0009_convite_inscricaodesfile_convite"),
    ]

    operations = [
        migrations.AddField(
            model_name="convite",
            name="convidados_confirmados",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Confirmados"
            ),
        ),
        migrations.AlterField(
            model_name="convite",
            name="hash",
            field=models.CharField(
                default="", editable=False, max_length=8, verbose_name="Hash"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inscricaodesfile",
            unique_together={("desfile", "pessoa")},
        ),
    ]
