# Generated by Django 5.0.2 on 2024-02-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desfiles", "0010_convite_convidados_confirmados_alter_convite_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricaodesfile",
            name="tipo_pessoa",
            field=models.CharField(
                choices=[("C", "Convidado"), ("S", "Staff"), ("D", "Condutor")],
                default="C",
                max_length=1,
                verbose_name="Tipo",
            ),
        ),
    ]
