# Generated by Django 5.0.2 on 2024-02-10 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0011_inscricaodesfile_tipo_pessoa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPadraoVeiculo",
            fields=[
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="desfiles.veiculo",
                        verbose_name="Veículo",
                    ),
                ),
                (
                    "ultimo_ajuste",
                    models.DateTimeField(auto_now=True, verbose_name="Último ajuste"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
        ),
    ]
