# Generated by Django 5.0.2 on 2024-02-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0012_staffpadraoveiculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffpadraoveiculo",
            name="veiculo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                serialize=False,
                to="desfiles.veiculo",
                verbose_name="Veículo",
            ),
        ),
        migrations.CreateModel(
            name="StaffPadrao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pessoa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
                (
                    "staff_padrao_veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.staffpadraoveiculo",
                        verbose_name="staff padrão",
                    ),
                ),
            ],
        ),
    ]
