# Generated by Django 5.0.2 on 2024-02-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0013_alter_staffpadraoveiculo_veiculo_staffpadrao"),
    ]

    operations = [
        migrations.CreateModel(
            name="PessoaStaff",
            fields=[],
            options={
                "verbose_name": "Pessoa staff",
                "verbose_name_plural": "Pessoas staff",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("desfiles.pessoa",),
        ),
        migrations.AlterModelOptions(
            name="staffpadrao",
            options={
                "verbose_name": "Staff padrão",
                "verbose_name_plural": "Staffs padrão",
            },
        ),
        migrations.AlterModelOptions(
            name="staffpadraoveiculo",
            options={
                "verbose_name": "Staff padrão por veículo",
                "verbose_name_plural": "Staffs padrão por veículo",
            },
        ),
        migrations.AddField(
            model_name="staffpadraoveiculo",
            name="pessoas",
            field=models.ManyToManyField(
                to="desfiles.staffpadrao", verbose_name="Pessoas"
            ),
        ),
    ]
