# Generated by Django 5.0.2 on 2024-02-11 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0014_pessoastaff_alter_staffpadrao_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="staffpadrao",
            unique_together={("staff_padrao_veiculo", "pessoa")},
        ),
    ]
