# Generated by Django 5.0.2 on 2024-02-15 11:07

import desfiles.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0015_alter_staffpadrao_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Logotipo para ser usada nos relatórios",
                null=True,
                upload_to=desfiles.models_utils.upload_to,
                verbose_name="Imagem",
            ),
        ),
    ]
