# Generated by Django 5.0.2 on 2024-02-16 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0017_grupo_anfitrioes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pessoa",
            options={"permissions": [("pode_convidar", "Pode convidar")]},
        ),
    ]
