# Generated by Django 5.0.2 on 2024-02-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0018_alter_pessoa_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("value", models.CharField(max_length=250)),
            ],
        ),
    ]
