# Generated by Django 5.0.2 on 2024-02-18 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0021_alter_config_options_inscricaodesfile_grupo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "when",
                    models.DateTimeField(auto_now_add=True, verbose_name="Quando"),
                ),
                ("message", models.CharField(max_length=250, verbose_name="Mensagem")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Lida"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("I", "Informação"), ("W", "Alerta"), ("E", "Erro")],
                        default="I",
                        max_length=1,
                        verbose_name="Nível",
                    ),
                ),
                (
                    "user_from",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_from",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Remetente",
                    ),
                ),
                (
                    "user_to",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_to",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "indexes": [models.Index(fields=["user_to", "when"], name="idx_msg")],
            },
        ),
    ]
