# Generated by Django 5.0.2 on 2024-02-25 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0023_usermessage_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="PessoaLocalizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "when",
                    models.DateTimeField(auto_now_add=True, verbose_name="Quando"),
                ),
                ("ip", models.GenericIPAddressField(verbose_name="IP")),
                ("pais", models.CharField(max_length=20, verbose_name="País")),
                ("estado", models.CharField(max_length=30, verbose_name="Estado")),
                ("cidade", models.CharField(max_length=30, verbose_name="Cidade")),
                (
                    "pessoa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
        ),
    ]
