# Generated by Django 5.0.2 on 2024-02-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0024_pessoalocalizacao"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pessoalocalizacao",
            index=models.Index(fields=["pessoa", "when"], name="idx_loc"),
        ),
    ]
