# Generated by Django 5.0.2 on 2024-02-25 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0025_pessoalocalizacao_idx_loc"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pessoalocalizacao",
            options={
                "verbose_name": "Localização",
                "verbose_name_plural": "Localizações",
            },
        ),
        migrations.CreateModel(
            name="PessoaRevisarSenha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_solicitacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data solicitação"
                    ),
                ),
                (
                    "atendida_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Atendida em"
                    ),
                ),
                (
                    "atendida_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atendida por",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="desfiles.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
        ),
    ]
