# Generated by Django 5.0.2 on 2024-02-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0026_alter_pessoalocalizacao_options_pessoarevisarsenha"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoarevisarsenha",
            name="ativa",
            field=models.BooleanField(default=True, verbose_name="Ativa"),
        ),
    ]
