# Generated by Django 5.0.2 on 2024-02-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0027_pessoarevisarsenha_ativa"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessage",
            name="link",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Link"
            ),
        ),
    ]
