# Generated by Django 5.0.2 on 2024-02-27 00:34

import desfiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0028_usermessage_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoarevisarsenha",
            name="guid",
            field=models.CharField(
                default=desfiles.models.create_guid, max_length=36, verbose_name="GUID"
            ),
        ),
    ]
