# Generated by Django 5.0.2 on 2024-02-27 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0029_pessoarevisarsenha_guid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pessoarevisarsenha",
            index=models.Index(fields=["guid"], name="idx_guid"),
        ),
    ]
