# Generated by Django 5.0.2 on 2024-02-27 00:39

import desfiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0030_pessoarevisarsenha_idx_guid"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pessoarevisarsenha",
            name="idx_guid",
        ),
        migrations.RemoveField(
            model_name="pessoarevisarsenha",
            name="id",
        ),
        migrations.AlterField(
            model_name="pessoarevisarsenha",
            name="guid",
            field=models.CharField(
                default=desfiles.models.create_guid,
                max_length=36,
                primary_key=True,
                serialize=False,
                verbose_name="GUID",
            ),
        ),
    ]
