# Generated by Django 5.0.2 on 2024-02-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0032_alter_pessoarevisarsenha_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trajeinventario",
            name="ultima_atualizacao",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última atualização"
            ),
        ),
    ]
