# Generated by Django 5.0.2 on 2024-03-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0033_trajeinventario_ultima_atualizacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pessoa",
            options={
                "permissions": [
                    (
                        "cus_pode_convidar",
                        "Usuário tem permissão de criar e enviar convites",
                    ),
                    (
                        "cus_almoxarife",
                        "Efetua empréstimo, recebimento, avaliação e manutenção de trajes, e recebimento das taxas de uso",
                    ),
                    (
                        "cus_adm_pessoas",
                        "Gerencia as pessoas cadastradas, quanto aos papéis e permissões",
                    ),
                ]
            },
        ),
        migrations.AlterField(
            model_name="trajeinventario",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("D", "Disponível"),
                    ("E", "Emprestado"),
                    ("M", "Em Manutenção"),
                    ("X", "Descartado"),
                    ("x", "Extraviado"),
                ],
                editable=False,
                max_length=1,
                verbose_name="Situação",
            ),
        ),
    ]
