# Generated by Django 5.0.2 on 2024-03-04 12:22

import desfiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0034_alter_pessoa_options_alter_trajeinventario_situacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="traje",
            name="campos_checklist",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Cada linha é um ítem a ser verificado na entrega e devolução do traje",
                max_length=2048,
                validators=[desfiles.models.campos_checklist_validator],
                verbose_name="Lista de verificação",
            ),
        ),
    ]
