# Generated by Django 5.0.2 on 2024-03-08 00:30

from django.db import migrations, models


def fix_nome_busca(apps, schema_editor):
    Pessoa = apps.get_model("desfiles", "Pessoa")
    for pessoa in Pessoa.objects.filter(grupo=None):
        pessoa.save()  # Save força a atualização de nome_busca


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0037_desfile_obs_desfile_obs_convidado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="nome_busca",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=60,
                null=True,
                verbose_name="Nome busca",
            ),
        ),
        migrations.RunPython(fix_nome_busca, migrations.RunPython.noop),
    ]
