# Generated by Django 5.0.2 on 2024-03-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0039_desfile_situacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trajehistorico",
            name="obs",
            field=models.TextField(
                default="", max_length=120, verbose_name="Observações"
            ),
        ),
    ]
