# Generated by Django 5.0.3 on 2024-03-12 12:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desfiles", "0040_alter_trajehistorico_obs"),
    ]

    operations = [
        migrations.AddField(
            model_name="desfile",
            name="valor_taxa_traje",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Taxa do traje",
            ),
        ),
    ]
